from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EvaluationItem(BaseModel):
    """Single evaluation item input for judging pipeline."""

    id: str = Field(description="Unique evaluation case identifier")
    input: str = Field(description="User prompt / question input")
    system_prompt: Optional[str] = Field(default="", description="System prompt provided to generator")
    model_output: str = Field(description="Candidate response generated by the model")
    expected_output: Optional[str] = Field(default=None, description="Ground truth / reference output")
    criteria: Optional[List[str]] = Field(
        default_factory=lambda: ["correctness", "faithfulness", "completeness", "instruction_following", "tone_safety"],
        description="Explicit evaluation criteria list",
    )
    category: Optional[str] = Field(default="general", description="Evaluation test category")


class CriterionScore(BaseModel):
    """Per-criterion score and rationale awarded by the LLM Judge."""

    criterion: str = Field(description="Name of the evaluated criterion")
    score: float = Field(ge=1.0, le=5.0, description="Numerical score bounded from 1.0 to 5.0")
    rationale: str = Field(description="Specific evidence-based reasoning for the score")


class JudgeVerdict(BaseModel):
    """Structured quality verdict output by the LLM Judge for a single item."""

    question_id: str = Field(description="Unique case identifier")
    category: str = Field(default="general", description="Evaluation category")
    criteria_scores: Dict[str, CriterionScore] = Field(
        description="Dictionary mapping criterion name to CriterionScore"
    )
    overall_score: float = Field(ge=1.0, le=5.0, description="Python-calculated mean overall quality score (1.0 to 5.0, rounded to 1 decimal place)")
    llm_overall_score: Optional[float] = Field(default=None, description="Raw overall_score returned by LLM Judge (retained for audit/debugging)")
    passed: bool = Field(description="Flag indicating if Python overall_score >= pass_score_threshold")
    summary_rationale: str = Field(description="Overall verdict summary")
    raw_response: str = Field(default="", description="Raw judge LLM text output for auditability")
    latency_ms: float = Field(default=0.0, description="Execution latency in milliseconds")
    parsed_fallback: bool = Field(default=False, description="Flag indicating if fallback parser was triggered")


class ABComparisonItem(BaseModel):
    """Pairwise A/B comparison test item."""

    id: str = Field(description="Unique A/B evaluation case identifier")
    input: str = Field(description="User prompt / question input")
    system_prompt: Optional[str] = Field(default="", description="System prompt")
    candidate_a_output: str = Field(description="Output from Candidate / Configuration A")
    candidate_b_output: str = Field(description="Output from Candidate / Configuration B")
    expected_output: Optional[str] = Field(default=None, description="Reference output")


class ABVerdict(BaseModel):
    """Pairwise A/B comparison verdict."""

    question_id: str = Field(description="Unique case identifier")
    winner: str = Field(description="Winner declaration: 'A', 'B', or 'Tie'")
    score_a: float = Field(ge=1.0, le=5.0, description="Score awarded to Candidate A")
    score_b: float = Field(ge=1.0, le=5.0, description="Score awarded to Candidate B")
    rationale: str = Field(description="Comparative reasoning for verdict")
    latency_ms: float = Field(default=0.0, description="Execution latency in milliseconds")


class SuiteReport(BaseModel):
    """Aggregated evaluation suite report."""

    total_cases: int = Field(description="Total evaluated cases")
    passed_cases: int = Field(description="Count of passing cases")
    failed_cases: int = Field(description="Count of failing cases")
    pass_rate: float = Field(description="Fraction of passing cases (0.0 to 1.0)")
    mean_overall_score: float = Field(description="Mean overall score across all cases")
    mean_criterion_scores: Dict[str, float] = Field(
        default_factory=dict, description="Mean score per individual criterion"
    )
    category_scores: Dict[str, Any] = Field(
        default_factory=dict, description="Per-category score breakdown"
    )
    verdicts: List[JudgeVerdict] = Field(default_factory=list, description="Per-item verdicts")


class ABSuiteReport(BaseModel):
    """Aggregated A/B comparison suite report."""

    total_cases: int = Field(description="Total A/B comparison cases")
    wins_a: int = Field(description="Wins for Candidate A")
    wins_b: int = Field(description="Wins for Candidate B")
    ties: int = Field(description="Count of ties")
    win_rate_a: float = Field(description="Win rate for Candidate A (excluding ties)")
    win_rate_b: float = Field(description="Win rate for Candidate B (excluding ties)")
    overall_winner: str = Field(description="Overall winning candidate ('A', 'B', or 'Tie')")
    verdicts: List[ABVerdict] = Field(default_factory=list, description="Per-case A/B verdicts")


class PositionBiasResult(BaseModel):
    """Position bias measurement results (A-B vs B-A swap)."""

    total_pairs: int = Field(description="Total evaluated A/B pairs")
    original_winners: List[str] = Field(description="Winning candidates in original order (A/B/Tie)")
    swapped_winners: List[str] = Field(description="Winning candidates in swapped order (A/B/Tie)")
    flips: int = Field(description="Count of position-driven winner flips")
    flip_rate: float = Field(description="Flip rate fraction (flips / total_pairs)")


class VerbosityBiasResult(BaseModel):
    """Verbosity/length bias measurement results."""

    normal_mean_score: float = Field(description="Mean score for normal answers")
    verbose_mean_score: float = Field(description="Mean score for padded verbose answers")
    score_delta: float = Field(description="Score difference (verbose - normal)")
    verbosity_biased: bool = Field(description="Flag indicating if verbosity artificially increased score")


class SycophancyResult(BaseModel):
    """Sycophancy/confident-wrong probe results."""

    total_cases: int = Field(description="Count of confident-wrong cases evaluated")
    detected_correctly: int = Field(description="Count of confident-wrong cases correctly given low score (<=2.5)")
    detection_rate: float = Field(description="Rate at which judge correctly detected and penalized wrong answers (0.0 to 1.0)")
    sycophancy_rate: float = Field(description="Rate of sycophantic acceptance where wrong answers were given high scores (0.0 to 1.0)")


class ScoreClusteringResult(BaseModel):
    """Score distribution and spread metrics."""

    min_score: float = Field(description="Minimum overall score")
    max_score: float = Field(description="Maximum overall score")
    score_std_dev: float = Field(description="Standard deviation of overall scores")
    score_counts: Dict[str, int] = Field(description="Distribution histogram of integer score buckets (1 to 5)")
    is_clustered: bool = Field(description="Flag indicating if scores are severely clustered (std < 0.5)")


class BiasReport(BaseModel):
    """Aggregated bias measurements report."""

    position_bias: PositionBiasResult
    verbosity_bias: VerbosityBiasResult
    sycophancy_bias: SycophancyResult
    score_clustering: ScoreClusteringResult


class CaseValidationComparison(BaseModel):
    """Per-case comparison between Run 1 and Run 2 for test-retest validation."""

    question_id: str = Field(description="Case identifier")
    run1_score: float = Field(description="Python-calculated overall score in Run 1")
    run2_score: float = Field(description="Python-calculated overall score in Run 2")
    run1_passed: bool = Field(description="Passed flag in Run 1")
    run2_passed: bool = Field(description="Passed flag in Run 2")
    score_delta: float = Field(description="Absolute difference in overall score")
    unchanged: bool = Field(description="Flag indicating if verdict and score remained consistent")


class ValidationReport(BaseModel):
    """Aggregated test-retest consistency validation report."""

    total_cases: int = Field(description="Total evaluated cases")
    unchanged_cases: int = Field(description="Count of cases with identical verdict and score")
    changed_cases: int = Field(description="Count of cases with changed verdict or score")
    consistency_rate: float = Field(description="Fraction of unchanged cases (0.0 to 1.0)")
    mean_score_delta: float = Field(description="Mean absolute overall score delta between Run 1 and Run 2")
    judge_model: str = Field(description="Judge model evaluated")
    temperature: float = Field(description="Sampling temperature")
    case_comparisons: List[CaseValidationComparison] = Field(
        default_factory=list, description="Per-case comparison details"
    )
