from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EvaluationItem(BaseModel):
    """Single evaluation item input for judging pipeline."""

    id: str = Field(description="Unique evaluation case identifier")
    input: str = Field(description="User prompt / question input")
    system_prompt: Optional[str] = Field(default="", description="System prompt provided to generator")
    model_output: str = Field(description="Candidate response generated by the model")
    expected_output: Optional[str] = Field(default=None, description="Ground truth / reference output")
    criteria: Optional[List[str]] = Field(
        default_factory=lambda: ["correctness", "faithfulness", "completeness", "instruction_following", "tone_safety"],
        description="Explicit evaluation criteria list",
    )
    category: Optional[str] = Field(default="general", description="Evaluation test category")


class CriterionScore(BaseModel):
    """Per-criterion score and rationale awarded by the LLM Judge."""

    criterion: str = Field(description="Name of the evaluated criterion")
    score: float = Field(ge=1.0, le=5.0, description="Numerical score bounded from 1.0 to 5.0")
    rationale: str = Field(description="Specific evidence-based reasoning for the score")


class JudgeVerdict(BaseModel):
    """Structured quality verdict output by the LLM Judge for a single item."""

    question_id: str = Field(description="Unique case identifier")
    criteria_scores: Dict[str, CriterionScore] = Field(
        description="Dictionary mapping criterion name to CriterionScore"
    )
    overall_score: float = Field(ge=1.0, le=5.0, description="Aggregate overall quality score (1.0 to 5.0)")
    passed: bool = Field(description="Flag indicating if overall_score >= pass_score_threshold")
    summary_rationale: str = Field(description="Overall verdict summary")
    raw_response: str = Field(default="", description="Raw judge LLM text output for auditability")
    latency_ms: float = Field(default=0.0, description="Execution latency in milliseconds")
    parsed_fallback: bool = Field(default=False, description="Flag indicating if fallback parser was triggered")


class ABComparisonItem(BaseModel):
    """Pairwise A/B comparison test item."""

    id: str = Field(description="Unique A/B evaluation case identifier")
    input: str = Field(description="User prompt / question input")
    system_prompt: Optional[str] = Field(default="", description="System prompt")
    candidate_a_output: str = Field(description="Output from Candidate / Configuration A")
    candidate_b_output: str = Field(description="Output from Candidate / Configuration B")
    expected_output: Optional[str] = Field(default=None, description="Reference output")


class ABVerdict(BaseModel):
    """Pairwise A/B comparison verdict."""

    question_id: str = Field(description="Unique case identifier")
    winner: str = Field(description="Winner declaration: 'A', 'B', or 'Tie'")
    score_a: float = Field(ge=1.0, le=5.0, description="Score awarded to Candidate A")
    score_b: float = Field(ge=1.0, le=5.0, description="Score awarded to Candidate B")
    rationale: str = Field(description="Comparative reasoning for verdict")
    latency_ms: float = Field(default=0.0, description="Execution latency in milliseconds")


class SuiteReport(BaseModel):
    """Aggregated evaluation suite report."""

    total_cases: int = Field(description="Total evaluated cases")
    passed_cases: int = Field(description="Count of passing cases")
    failed_cases: int = Field(description="Count of failing cases")
    pass_rate: float = Field(description="Fraction of passing cases (0.0 to 1.0)")
    mean_overall_score: float = Field(description="Mean overall score across all cases")
    mean_criterion_scores: Dict[str, float] = Field(
        default_factory=dict, description="Mean score per individual criterion"
    )
    category_scores: Dict[str, Dict[str, float]] = Field(
        default_factory=dict, description="Per-category score breakdown"
    )
    verdicts: List[JudgeVerdict] = Field(default_factory=list, description="Per-item verdicts")


class ABSuiteReport(BaseModel):
    """Aggregated A/B comparison suite report."""

    total_cases: int = Field(description="Total A/B comparison cases")
    wins_a: int = Field(description="Wins for Candidate A")
    wins_b: int = Field(description="Wins for Candidate B")
    ties: int = Field(description="Count of ties")
    win_rate_a: float = Field(description="Win rate for Candidate A (excluding ties)")
    win_rate_b: float = Field(description="Win rate for Candidate B (excluding ties)")
    overall_winner: str = Field(description="Overall winning candidate ('A', 'B', or 'Tie')")
    verdicts: List[ABVerdict] = Field(default_factory=list, description="Per-case A/B verdicts")


class PositionBiasResult(BaseModel):
    """Position bias measurement results (A-B vs B-A swap)."""

    total_pairs: int = Field(description="Total evaluated A/B pairs")
    original_winners: List[str] = Field(description="Winning candidates in original order (A/B/Tie)")
    swapped_winners: List[str] = Field(description="Winning candidates in swapped order (A/B/Tie)")
    flips: int = Field(description="Count of position-driven winner flips")
    flip_rate: float = Field(description="Flip rate fraction (flips / total_pairs)")


class VerbosityBiasResult(BaseModel):
    """Verbosity/length bias measurement results."""

    normal_mean_score: float = Field(description="Mean score for normal answers")
    verbose_mean_score: float = Field(description="Mean score for padded verbose answers")
    score_delta: float = Field(description="Score difference (verbose - normal)")
    verbosity_biased: bool = Field(description="Flag indicating if verbosity artificially increased score")


class SycophancyResult(BaseModel):
    """Sycophancy/confident-wrong probe results."""

    total_cases: int = Field(description="Count of confident-wrong cases evaluated")
    detected_correctly: int = Field(description="Count of confident-wrong cases correctly given low score (<=2)")
    sycophancy_rate: float = Field(description="Rate of sycophantic acceptance (wrong given high score)")


class ScoreClusteringResult(BaseModel):
    """Score distribution and spread metrics."""

    min_score: float = Field(description="Minimum overall score")
    max_score: float = Field(description="Maximum overall score")
    score_std_dev: float = Field(description="Standard deviation of overall scores")
    score_counts: Dict[str, int] = Field(description="Distribution histogram of integer score buckets (1 to 5)")
    is_clustered: bool = Field(description="Flag indicating if scores are severely clustered (std < 0.5)")


class BiasReport(BaseModel):
    """Aggregated bias measurements report."""

    position_bias: PositionBiasResult
    verbosity_bias: VerbosityBiasResult
    sycophancy_bias: SycophancyResult
    score_clustering: ScoreClusteringResult
